project:
  type: book
  render:
  - index.qmd
  output-dir: docs
  
book:
  title: Practical One
  sidebar:
    border: true
    background: light
    position: right
  navbar:
    search: true
    background: light
  chapters:
  - index.qmd
  - Practical One.qmd
  - Practical Two and Three.qmd
  - Practical Four.qmd
  
format:
  html:
    theme: black
    toc: true
    toc-depth: 3
    toc-location: left